### ISSUE TITLE
Question - How can I get a wrapped version of base64?

### ISSUE THREAD

**Issue by kirtan403** [riyadhalnur/node-base64-image#12]
Currently it returns base64 encoded string of an image. It is a long line of a string. In MIME types the base64 encoded strings are wrapped at 76 characters. Any option to directly get that? 

For example, there are multiple types of base64 encoded strings. You can find those in the Android Base64 class [here](http://developer.android.com/reference/android/util/Base64.html#CRLF). Is there any way to directly get any type of base64 (like wrapped or unwrapped)? If not, any plans to include that?

**Comment by riyadhalnur** [comment]
Currently, there's no option to wrap the encoded string. You can, however, get the actual `Buffer` object instead of the string as the output.

Thanks for the heads up though. I'll try to include it in the library down  the line. I'm doing a rewrite at the moment for the 1.0.0 release, so this is definitely something that can be included.

**Comment by ktkt1993** [comment]
Yes, this will be useful. Actually I am trying to use this with Android. So, doing it in wrapped version in both server side and app will eliminate any compatibility issues. This might help you out : [](http://stackoverflow.com/questions/36660118/how-to-get-mime-type-base64-encoded-string-in-nodejs/)

When is 1.0.0 release coming? Just asking so I can synchronize with my timeline, else I need to apply any temporary solution.

**Comment by riyadhalnur** [comment]
I can't give a firm timeline on the release but in the meantime, you can look into this module [https://github.com/connrs/node-mime-base64-stream](https://github.com/connrs/node-mime-base64-stream). Hope it helps.

**Comment by ktkt1993** [comment]
No problem. Thanks.

**Comment by riyadhalnur** [comment]
@ktkt1993 I decided on a due date to include this feature into the lib.

**Comment by ktkt1993** [comment]
Thanks @riyadhalnur ! May I know the due date?

**Comment by riyadhalnur** [comment]
Yeah, it for version 1.1.0. It's slated for the end of this month if all goes well.

**Comment by ktkt1993** [comment]
Cool ! Hope to see it as soon as possible! Good luck..
