### ISSUE TITLE
Custom headers?

### ISSUE THREAD

**Issue by josephrocca** [riyadhalnur/node-base64-image#18]
Unless I'm mistaken, you can't pass in custom headers for http requests? Because of this issue I couldn't use this library. maybe other people are in the same boat. Just a heads up.

Cheers

**Comment by riyadhalnur** [comment]
@josephrocca No, currently there's no support for custom headers. You've raised a good point though. Thank you. I'll look into putting this in the next release.

**Comment by josephrocca** [comment]
No worries :+1: while I've got you: a couple of simple "hello world" examples in the readme would also be helpful I think. Anyway, thanks for your work on this lib :)

**Comment by riyadhalnur** [comment]
Welcome and thank you for the suggestions. The examples will be included in the next release.
