### ISSUE TITLE
decode

### ISSUE THREAD

**Issue by fastbean-au** [riyadhalnur/node-base64-image#19]
encode outputs either a string or a buffer, while decode only accepts buffers - it should also accept a string for consistency.

**Comment by riyadhalnur** [comment]
You mean to say it should accept a Base64 string as well?

**Comment by fastbean-au** [comment]
Yes, I believe that it should - I should be able to decode(encode()) for both string and buffer.

**Comment by riyadhalnur** [comment]
Cool. Thank you the input. I'll see what I can do. 😃
