### ISSUE TITLE
decode adds extension to filename

### ISSUE THREAD

**Issue by fastbean-au** [riyadhalnur/node-base64-image#20]
decode automatically appends an extension to the filename, hard-coded to '.jpg'.  This is not a safe assumption to be made as either an extension may already be provided and/or the contents may not be a jpeg image.

**Comment by riyadhalnur** [comment]
Thank you. Will look into it.

**Comment by riyadhalnur** [comment]
Implementation details -
- [ ] Infer extension from data string. Can be overridden by `ext` option if declared explicitly.
- [ ] Save as `jpg` by default if Buffer
- [ ] Save to provided `ext` if provided and Buffer is the input

@fastbean-au Thoughts?

**Comment by intersides** [comment]
it 's in line 104 of node-base64-image.js

  (0, _fs.writeFile)(options.filename + '.jpg', imageBuffer, 'base64', function ...

instead of
  (0, _fs.writeFile)(options.filename, imageBuffer, 'base64', function ...
