### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by riyadhalnur** [riyadhalnur/node-base64-image#21]
As @josephrocca pointed out in #18, it would be nice to have example code.

**Comment by NeXTs** [comment]
```
base64.encode(url, options, function(err, image) {
  // image
})
```

**Comment by karimwarp** [comment]
> ```
> base64.encode(url, options, function(err, image) {
>   // image
> })
> ```

how can use this in an angular project?

**Comment by Y1a2s3h4** [comment]
Can you improve your documentation with All methods and examples?
