### ISSUE TITLE
new version to fix vulnerability

### ISSUE THREAD

**Issue by jmls** [riyadhalnur/node-base64-image#24]
if I npm install this package, the following deps get installed as well:

```
`-- node-base64-image@1.0.1 
  +-- polygoat@1.1.4 
  `-- request@2.72.0 
    +-- qs@6.1.0 
    `-- tough-cookie@2.2.2 
```

https://nodesecurity.io/advisories/130 advises to upgrade to tough-cookie 2.3 or higher, which request@2.74.0 does.

Although the package.json file was updated to use request@2.74.0, it seems like the npm version itself wasn't (still 1.0.1) so the npm install is still using the 2.72 version of request

Could you publish a new version to fix this vulnerability ? 

Thanks

**Comment by riyadhalnur** [comment]
@jmls Thanks for bringing this to my attention. I'll look in to it.

**Comment by riyadhalnur** [comment]
Just pushed v1.0.3 now. Everything should be up-to-date now. Thank you for bringing this to the forefront @jmls 🍻
