### ISSUE TITLE
Support image decode and encode to be rendered as an image source in an image tag

### ISSUE THREAD

**Issue by mbmelgo** [riyadhalnur/node-base64-image#25]
Can you support directly decoding an image from a image tag source and also encoding a base64 data from a data base to render directly as a source in an image tag

**Comment by riyadhalnur** [comment]
Do you mean by extracting an image URL from the HTML? If so, the intention of this library is not to parse HTML images tags for image URL and encode/decode them.

**Comment by mbmelgo** [comment]
What I mean was I have a program that accepts image upload and from that upload I would like to convert/encode it to base64 and put the result (base64) to a database, and in another aspect of my program I would like to retrieve that base64 from the database and re render it as an image source for an image tag without saving/making a file out of it. Is it possible?

**Comment by riyadhalnur** [comment]
Ah, ok thanks for the clarification. Yes, you can definitely do what you described. Once you receive the uploaded image on the server, you can pass it in to the `encode` function and save the output from the `callback` as you see fit and vice versa for decoding. For decoding though, since you will get a file back in return from the `callback`, you can directly serve the resulting file to the client.

**Comment by mbmelgo** [comment]
Okay, Thank you for the quick response and I hope you can make sample codes in implementing. :+1:

**Comment by riyadhalnur** [comment]
Cheers mate. Here's some pseudo code on how you could go about implementing the functionality -
```js
const base64 = require('node-base64-image');

app.post((req, res) => {
  // assuming req.body.image is a local file path or an image URL
  base64.encode(req.body.image, {string: true}, (err, img) => {
    if (err) {
      //handle error
    }

    db.insert({image: img})
      .then((data) => { res.json({data}); })
      .catch((err) => { // handle error });
});
```
