### ISSUE TITLE
Is node-base64-image written in typescript?!?!?

### ISSUE THREAD

**Issue by dherges** [riyadhalnur/node-base64-image#29]
* node version: n/a
* npm version: n/a

### Error output

I am curious: https://github.com/riyadhalnur/node-base64-image/blob/master/src/node-base64-image.js#L27

```js
type Callback<T> = (err: ?Error, x?: T) => void;

export function encode(url: string, options: Object = {string: false, local: false}, callback: Callback<mixed>) {
```

### More details

The code pretty much looks like TypeScript!

But there is no `tsconfig.json` in the repo, or am I blind? And the code is in  a `.js` file (not a `.ts`). So what is this?!? I am curious!

**Comment by riyadhalnur** [comment]
It's actually written in plain JS with Flow to add static type checking. Flow and TS do look very similar except for a few differences here and there.
