### ISSUE TITLE
Error: Cannot resolve module 'fs'

### ISSUE THREAD

**Issue by afilp** [riyadhalnur/node-base64-image#33]
* node version:  9.3.0
* npm version:   4.6.1

### Error output
```
Module not found: Error: Cannot resolve module 'fs' in E:\R\exclusivi-dashboard\node_modules\node-base64-image\dist
```

Using it in browser, with `webpack-dev-server`

**Comment by riyadhalnur** [comment]
This issue is a `webpack` specific error. You can go through this [issue](https://github.com/webpack-contrib/css-loader/issues/447) for a possible fix.
