### ISSUE TITLE
incorrect code in examples

### ISSUE THREAD

**Issue by non4me** [riyadhalnur/node-base64-image#4]
Hi
Thank for you module.
But correct your examples code please.

## Ex.1
var options = {string: true}  

base64.base64encode('www.someurl.com/image.jpg', function (err, image) {  
    if (err) { console.log(err); }  
    console.log(image);  
});  

MUST

var options = {string: true}  

base64.base64encode**r**('www.someurl.com/image.jpg', **options,** function (err, image) {  
    if (err) { console.log(err); }  
    console.log(image);  
});  

## Ex.2
base64.base64encode(  --> base64.base64encode**r**(

**Comment by riyadhalnur** [comment]
@non4me there's a PR #2 open for this already but there are some issues in there to fix before I can merge in to master
