### ISSUE TITLE
Error not returned from base64encoder if image doesn't exist

### ISSUE THREAD

**Issue by prointeg** [riyadhalnur/node-base64-image#5]
I have encountered this issue when encoding some images from a URL. 
I was trialling your component and iterating over an array of images URLs.
The number is encoded strings I received was one less than the number of items in the array.
No error was reported but I found that my source array had a misspelling on one of the images.
The path was correct, the filename was not.

**Comment by riyadhalnur** [comment]
I don't consider checking for correct filenames or paths to be a part of the scope of this module.

**Comment by prointeg** [comment]
OK no problem, good thing to have in the notes however. Other than that your module appears to work fine for the test I have made. Thanks.

**Comment by riyadhalnur** [comment]
Sure, I can put that down in the *README* as something to keep in mind when using this module. Thanks for using this module. Happy to hear your tests went well.
