### ISSUE TITLE
local files url not accessing

### ISSUE THREAD

**Issue by dilanhag** [riyadhalnur/node-base64-image#58]
* node version: 10.23.0
* npm version:6.14.8

### Error output
```
ECONNREFUSED
```
im trying to encode image from local url
const url = 'file:///C:/Users/'my pc user name"/Desktop/ImageDecordEncorder/src/assets/images/example.jpg';

working fine with global url

**Comment by riyadhalnur** [comment]
The path seems wrong - there's no need for the `file:///` prefix
