### ISSUE TITLE
Trying to get in touch with you regarding a security issue

### ISSUE THREAD

**Issue by huntr-helper** [riyadhalnur/node-base64-image#59]
Hi there,

I couldn't find a `SECURITY.md` in your repository and so am not sure how to best contact you privately to disclose the security issue.

Can you add a `SECURITY.md` file with your e-mail to your repository, so that I know who to contact? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, please let me know so I can ping you the info.

Thanks! (cc @JamieSlome)

**Comment by JamieSlome** [comment]
@riyadhalnur - thanks for creating the `SECURITY.md`! You can view the 4 reports directly here:

https://huntr.dev/bounties/1625485716124-riyadhalnur/node-base64-image/
https://huntr.dev/bounties/1625486069586-riyadhalnur/node-base64-image/
https://huntr.dev/bounties/1625486747136-riyadhalnur/node-base64-image/
https://huntr.dev/bounties/1625486403686-riyadhalnur/node-base64-image/

They are private and only accessible to you. Let me know if you have any questions! ❤️
